# Generated by Django 5.2.3 on 2025-07-14 09:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_retrait', models.CharField(editable=False, help_text='Code de retrait unique', max_length=20, unique=True)),
                ('qr_code', models.CharField(editable=False, help_text='Code QR pour validation', max_length=100, unique=True)),
                ('montant_retire', models.DecimalField(decimal_places=2, help_text='Montant retiré par le bénéficiaire', max_digits=15)),
                ('commission_agent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Commission de l'agent", max_digits=10)),
                ('frais_retrait', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frais de retrait facturés au client', max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=12)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_retrait', models.DateTimeField(blank=True, help_text='Date effective du retrait', null=True)),
                ('piece_identite_verifie', models.BooleanField(default=False, help_text="Pièce d'identité vérifiée par l'agent")),
                ('code_sms_verifie', models.BooleanField(default=False, help_text='Code SMS de vérification validé')),
                ('notes_verification', models.TextField(blank=True, help_text="Notes de l'agent sur la vérification")),
                ('latitude_retrait', models.DecimalField(blank=True, decimal_places=6, help_text='Localisation GPS du retrait', max_digits=9, null=True)),
                ('longitude_retrait', models.DecimalField(blank=True, decimal_places=6, help_text='Localisation GPS du retrait', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='Agent qui effectue le retrait', on_delete=django.db.models.deletion.CASCADE, related_name='retraits_geres', to='agents.agentlocal')),
                ('beneficiaire', models.ForeignKey(help_text="Utilisateur qui reçoit l'argent", on_delete=django.db.models.deletion.CASCADE, related_name='retraits_recus', to=settings.AUTH_USER_MODEL)),
                ('transaction_origine', models.ForeignKey(blank=True, help_text="Transaction d'origine qui génère ce retrait", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Retrait',
                'verbose_name_plural': 'Retraits',
                'db_table': 'withdrawals',
                'ordering': ['-date_demande'],
                'indexes': [models.Index(fields=['statut', 'date_demande'], name='withdrawals_statut_7c0587_idx'), models.Index(fields=['agent', 'date_demande'], name='withdrawals_agent_i_a3830f_idx'), models.Index(fields=['beneficiaire', 'date_demande'], name='withdrawals_benefic_95b9bc_idx'), models.Index(fields=['code_retrait'], name='withdrawals_code_re_e7455d_idx')],
            },
        ),
    ]
