# Generated by Django 5.2.3 on 2025-07-13 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycdocument',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Document KYC', 'verbose_name_plural': 'Documents KYC'},
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_image',
            field=models.ImageField(upload_to='kyc_docs/', verbose_name='Image du Document'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_number',
            field=models.CharField(max_length=50, verbose_name='Numéro de Document'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PASSPORT', 'Passeport')], max_length=10, verbose_name='Type de Document'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Soumis le'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
