# Generated by Django 5.2.3 on 2025-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdocument',
            name='document_image',
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='document_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_docs/', verbose_name='Image du Document (Verso)'),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='document_front_image',
            field=models.ImageField(default=1, upload_to='kyc_docs/', verbose_name='Image du Document (Recto)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='selfie_image',
            field=models.ImageField(default=1, upload_to='kyc_selfies/', verbose_name='Selfie avec le Document'),
            preserve_default=False,
        ),
    ]
