# Generated by Django 5.2.3 on 2025-07-14 09:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetriqueTempReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_metrique', models.CharField(max_length=50, unique=True)),
                ('valeur_numerique', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('valeur_texte', models.TextField(blank=True)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrique Temps Réel',
                'verbose_name_plural': 'Métriques Temps Réel',
            },
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_transactions', models.IntegerField(default=0, help_text='Nombre total de transactions du jour')),
                ('total_volume', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Volume total en XOF', max_digits=20)),
                ('total_commissions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total des commissions', max_digits=15)),
                ('taux_reussite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taux de réussite des transactions', max_digits=5)),
                ('nouveaux_utilisateurs', models.IntegerField(default=0, help_text='Nouveaux utilisateurs inscrits')),
                ('utilisateurs_actifs', models.IntegerField(default=0, help_text='Utilisateurs ayant fait au moins 1 transaction')),
                ('utilisateurs_kyc_verifies', models.IntegerField(default=0, help_text='Utilisateurs avec KYC vérifié')),
                ('agents_actifs', models.IntegerField(default=0, help_text='Agents actifs dans la journée')),
                ('total_retraits', models.IntegerField(default=0, help_text='Nombre de retraits effectués')),
                ('volume_retraits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Volume des retraits en XOF', max_digits=15)),
                ('transactions_wave', models.IntegerField(default=0, help_text='Transactions via Wave')),
                ('transactions_orange', models.IntegerField(default=0, help_text='Transactions via Orange Money')),
                ('taux_succes_wave', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taux de succès Wave', max_digits=5)),
                ('taux_succes_orange', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taux de succès Orange Money', max_digits=5)),
                ('transactions_internationales', models.IntegerField(default=0, help_text='Transactions internationales')),
                ('volume_international', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Volume international en XOF', max_digits=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistique Dashboard',
                'verbose_name_plural': 'Statistiques Dashboard',
                'db_table': 'dashboard_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='dashboard_s_date_87151c_idx'), models.Index(fields=['-date'], name='dashboard_s_date_9ea92c_idx')],
            },
        ),
    ]
