# Generated by Django 5.2.3 on 2025-07-14 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_reception', models.CharField(help_text='Code de réception pour le destinataire', max_length=20, unique=True)),
                ('montant_a_recevoir', models.DecimalField(decimal_places=2, help_text='Montant que le destinataire va recevoir', max_digits=15)),
                ('devise_reception', models.CharField(default='XOF', help_text='Devise de réception', max_length=3)),
                ('mode_reception', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('WESTERN_UNION', 'Western Union'), ('AGENT_LOCAL', 'Agent Local')], help_text="Mode choisi pour recevoir l'argent", max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('NOTIFIE', 'Notifié'), ('CONFIRME', 'Confirmé'), ('RETIRE', 'Retiré')], default='EN_ATTENTE', max_length=12)),
                ('date_notification', models.DateTimeField(blank=True, help_text="Date d'envoi de la notification", null=True)),
                ('date_confirmation', models.DateTimeField(blank=True, help_text='Date de confirmation par le destinataire', null=True)),
                ('date_retrait', models.DateTimeField(blank=True, help_text='Date effective du retrait', null=True)),
                ('notification_envoyee', models.BooleanField(default=False, help_text='Notification système envoyée')),
                ('sms_envoye', models.BooleanField(default=False, help_text='SMS de notification envoyé')),
                ('email_envoye', models.BooleanField(default=False, help_text='Email de notification envoyé')),
                ('expediteur_nom', models.CharField(blank=True, help_text="Nom de l'expéditeur pour affichage", max_length=200)),
                ('expediteur_telephone', models.CharField(blank=True, help_text="Téléphone de l'expéditeur", max_length=20)),
                ('message_expediteur', models.TextField(blank=True, help_text="Message de l'expéditeur au destinataire")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal_paiement', models.ForeignKey(blank=True, help_text='Canal de paiement utilisé pour la réception', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to='transactions.canalpaiement')),
                ('destinataire', models.ForeignKey(help_text="Utilisateur qui reçoit l'argent", on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to=settings.AUTH_USER_MODEL)),
                ('transaction_origine', models.OneToOneField(blank=True, help_text='Transaction qui génère cette réception', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Réception',
                'verbose_name_plural': 'Réceptions',
                'db_table': 'receptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['statut', 'date_notification'], name='receptions_statut_77fdbe_idx'), models.Index(fields=['destinataire', 'created_at'], name='receptions_destina_af74b2_idx'), models.Index(fields=['code_reception'], name='receptions_code_re_639fe0_idx')],
            },
        ),
    ]
