# Generated by Django 5.2.3 on 2025-07-14 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlocal',
            name='user',
            field=models.OneToOneField(help_text="Lien vers le compte utilisateur de l'agent", on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agentlocal',
            index=models.Index(fields=['statut_agent', 'latitude', 'longitude'], name='agents_loca_statut__98e4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='agentlocal',
            index=models.Index(fields=['statut_agent', 'heure_ouverture', 'heure_fermeture'], name='agents_loca_statut__4cd638_idx'),
        ),
    ]
