# Generated by Django 5.2.3 on 2025-07-13 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('TRANSACTION', 'Transaction'), ('ALERT', 'Alerte')], default='INFO', max_length=15, verbose_name='Type de Notification')),
                ('status', models.CharField(choices=[('UNREAD', 'Non lu'), ('READ', 'Lu')], default='UNREAD', max_length=10, verbose_name='Statut')),
                ('auto_sent', models.BooleanField(default=False, help_text='Indique si cette notification a été générée automatiquement', verbose_name='Envoi Automatique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('seen_at', models.DateTimeField(blank=True, help_text="Moment où l'utilisateur a vu cette notification", null=True, verbose_name='Vu le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
