# Generated by Django 5.2.3 on 2025-07-14 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalPaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal_name', models.CharField(max_length=50)),
                ('type_canal', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('KPAY', 'Kpay')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(max_length=50)),
                ('fees_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fees_fixed', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=500000.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canal de Paiement',
                'verbose_name_plural': 'Canaux de Paiement',
                'ordering': ['canal_name'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_iso', models.CharField(max_length=3, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('devise', models.CharField(max_length=3)),
                ('prefixe_tel', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('flag_emoji', models.CharField(default='🇸🇳', max_length=10)),
                ('limite_envoi_min', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('limite_envoi_max', models.DecimalField(decimal_places=2, default=500000, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='CorridorTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('temps_livraison_min', models.PositiveIntegerField(help_text='Minutes minimum')),
                ('temps_livraison_max', models.PositiveIntegerField(help_text='Minutes maximum')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('commission_fixe', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('montant_min_corridor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_max_corridor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nb_transactions', models.PositiveIntegerField(default=0)),
                ('volume_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_succes', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pays_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridors_entrants', to='transactions.pays')),
                ('pays_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridors_sortants', to='transactions.pays')),
            ],
            options={
                'unique_together': {('pays_origine', 'pays_destination')},
            },
        ),
        migrations.CreateModel(
            name='ServicePaiementInternational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('type_service', models.CharField(choices=[('MTN_MONEY', 'MTN Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('MOOV_MONEY', 'Moov Money'), ('WESTERN_UNION', 'Western Union'), ('MONEYGRAM', 'MoneyGram')], max_length=20)),
                ('code_service', models.CharField(max_length=10)),
                ('api_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('frais_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frais_fixe', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('frais_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frais_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('limite_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regex_telephone', models.CharField(help_text='Regex pour valider les numéros', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='transactions.pays')),
            ],
        ),
        migrations.CreateModel(
            name='TauxChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise_origine', models.CharField(max_length=3)),
                ('devise_destination', models.CharField(max_length=3)),
                ('taux', models.DecimalField(decimal_places=6, max_digits=12)),
                ('taux_inverse', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(default='xe.com', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('marge_achat', models.DecimalField(decimal_places=4, default=0.02, max_digits=5)),
                ('marge_vente', models.DecimalField(decimal_places=4, default=0.02, max_digits=5)),
            ],
            options={
                'indexes': [models.Index(fields=['devise_origine', 'devise_destination'], name='transaction_devise__50a423_idx'), models.Index(fields=['last_updated'], name='transaction_last_up_4219d1_idx')],
                'unique_together': {('devise_origine', 'devise_destination')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idTransaction', models.PositiveIntegerField(editable=False, help_text='Id numérique unique de la transaction', unique=True)),
                ('typeTransaction', models.CharField(choices=[('ENVOI', 'Envoi'), ('RECEPTION', 'Réception'), ('RETRAIT', 'Retrait'), ('RECHARGE', 'Recharge')], default='ENVOI', help_text='Le type de la transaction', max_length=15)),
                ('destinataire_phone', models.CharField(help_text='Numéro de téléphone du destinataire', max_length=20)),
                ('destinataire_nom', models.CharField(blank=True, help_text="Nom d'affichage du destinataire", max_length=100)),
                ('montantEnvoye', models.FloatField(help_text='Le montant envoyé')),
                ('montantConverti', models.FloatField(help_text='Le montant après conversion/frais')),
                ('statusTransaction', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('ACCEPTE', 'Accepté'), ('ENVOYE', 'Envoyé'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', help_text='Le statut de la transaction', max_length=15)),
                ('montantRecu', models.FloatField(help_text='Le montant reçu par le bénéficiaire')),
                ('deviseEnvoi', models.CharField(default='XOF', help_text="La devise de l'envoi", max_length=10)),
                ('deviseReception', models.CharField(default='XOF', help_text='La devise du reçu', max_length=10)),
                ('codeTransaction', models.CharField(help_text='Le code de la transaction', max_length=20, unique=True)),
                ('frais', models.CharField(help_text='Frais de la transaction', max_length=50)),
                ('dateTraitement', models.DateField(auto_now_add=True, help_text='Date de traitement de la transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal_paiement', models.ForeignKey(help_text='Canal de paiement utilisé', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.canalpaiement')),
                ('destinataire', models.ForeignKey(blank=True, help_text="L'utilisateur qui reçoit l'argent (si inscrit)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_recues', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(help_text="L'utilisateur qui envoie l'argent", on_delete=django.db.models.deletion.CASCADE, related_name='transactions_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionInternationale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_applique', models.DecimalField(decimal_places=6, max_digits=12)),
                ('montant_origine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_destination', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_service_origine', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frais_service_destination', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commission_corridor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frais_change', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reference_externe', models.CharField(blank=True, max_length=50)),
                ('temps_traitement_estime', models.PositiveIntegerField()),
                ('date_livraison_estimee', models.DateTimeField()),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.corridortransfert')),
                ('pays_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='transactions.pays')),
                ('pays_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envois', to='transactions.pays')),
                ('service_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_destination', to='transactions.servicepaiementinternational')),
                ('service_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_origine', to='transactions.servicepaiementinternational')),
                ('transaction_locale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension_internationale', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('nb_transactions', models.PositiveIntegerField(default=0)),
                ('derniere_transaction', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(help_text="L'utilisateur qui possède ce contact", on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaires', to=settings.AUTH_USER_MODEL)),
                ('user_correspondant', models.ForeignKey(blank=True, help_text="L'utilisateur correspondant à ce contact (si inscrit)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaire_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'verbose_name_plural': 'Bénéficiaires',
                'ordering': ['-derniere_transaction', '-nb_transactions', 'first_name'],
                'indexes': [models.Index(fields=['proprietaire', 'phone'], name='transaction_proprie_8d8057_idx'), models.Index(fields=['proprietaire', '-derniere_transaction'], name='transaction_proprie_1e42fc_idx')],
                'unique_together': {('proprietaire', 'phone')},
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['typeTransaction', 'statusTransaction'], name='transaction_typeTra_c692ab_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['expediteur', 'created_at'], name='transaction_expedit_bcc6fa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['destinataire', 'created_at'], name='transaction_destina_05f673_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['destinataire_phone'], name='transaction_destina_dafcbf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx'),
        ),
    ]
