# Generated by Django 5.2.3 on 2025-07-11 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'verbose_name_plural': 'Bénéficiaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanalPaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal_name', models.CharField(max_length=50)),
                ('type_canal', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('KPAY', 'Kpay')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(max_length=50)),
                ('fees_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fees_fixed', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=500000.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canal de Paiement',
                'verbose_name_plural': 'Canaux de Paiement',
                'ordering': ['canal_name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idTransaction', models.PositiveIntegerField(editable=False, help_text='Id numérique unique de la transaction', unique=True)),
                ('typeTransaction', models.CharField(choices=[('ENVOI', 'Envoi'), ('RECEPTION', 'Réception'), ('RETRAIT', 'Retrait'), ('RECHARGE', 'Recharge')], default='ENVOI', help_text='Le type de la transaction', max_length=15)),
                ('montantEnvoye', models.FloatField(help_text='Le montant envoyé')),
                ('montantConverti', models.FloatField(help_text='Le montant après conversion/frais')),
                ('statusTransaction', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('ACCEPTE', 'Accepté'), ('ENVOYE', 'Envoyé'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', help_text='Le statut de la transaction', max_length=15)),
                ('montantRecu', models.FloatField(help_text='Le montant reçu par le bénéficiaire')),
                ('deviseEnvoi', models.CharField(default='XOF', help_text="La devise de l'envoi", max_length=10)),
                ('deviseReception', models.CharField(default='XOF', help_text='La devise du reçu', max_length=10)),
                ('codeTransaction', models.CharField(help_text='Le code de la transaction', max_length=20, unique=True)),
                ('frais', models.CharField(help_text='Frais de la transaction', max_length=50)),
                ('dateTraitement', models.DateField(auto_now_add=True, help_text='Date de traitement de la transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['typeTransaction', 'statusTransaction'], name='transaction_typeTra_c692ab_idx'), models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx')],
            },
        ),
    ]
