# Generated by Django 5.2.3 on 2025-07-11 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiaire',
            options={'ordering': ['-derniere_transaction', '-nb_transactions', 'first_name'], 'verbose_name': 'Bénéficiaire', 'verbose_name_plural': 'Bénéficiaires'},
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='derniere_transaction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='nb_transactions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='proprietaire',
            field=models.ForeignKey(default=1, help_text="L'utilisateur qui possède ce contact", on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaires', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='user_correspondant',
            field=models.ForeignKey(blank=True, help_text="L'utilisateur correspondant à ce contact (si inscrit)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaire_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='canal_paiement',
            field=models.ForeignKey(default=1, help_text='Canal de paiement utilisé', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.canalpaiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='destinataire',
            field=models.ForeignKey(blank=True, help_text="L'utilisateur qui reçoit l'argent (si inscrit)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_recues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destinataire_nom',
            field=models.CharField(blank=True, help_text="Nom d'affichage du destinataire", max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destinataire_phone',
            field=models.CharField(default=1, help_text='Numéro de téléphone du destinataire', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='expediteur',
            field=models.ForeignKey(default=2, help_text="L'utilisateur qui envoie l'argent", on_delete=django.db.models.deletion.CASCADE, related_name='transactions_envoyees', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='beneficiaire',
            unique_together={('proprietaire', 'phone')},
        ),
        migrations.AddIndex(
            model_name='beneficiaire',
            index=models.Index(fields=['proprietaire', 'phone'], name='transaction_proprie_8d8057_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiaire',
            index=models.Index(fields=['proprietaire', '-derniere_transaction'], name='transaction_proprie_1e42fc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['expediteur', 'created_at'], name='transaction_expedit_bcc6fa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['destinataire', 'created_at'], name='transaction_destina_05f673_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['destinataire_phone'], name='transaction_destina_dafcbf_idx'),
        ),
    ]
