# Generated by Django 5.2.3 on 2025-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepaiementinternational',
            name='type_service',
            field=models.CharField(choices=[('MTN_MONEY', 'MTN Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('MOOV_MONEY', 'Moov Money'), ('WESTERN_UNION', 'Western Union'), ('MONEYGRAM', 'MoneyGram'), ('INWI_MONEY', 'Inwi Money'), ('OPAY', 'Opay'), ('VODAFONE_CASH', 'Vodafone Cash'), ('AIRTELTIGO_MONEY', 'AirtelTigo Money'), ('TIGO_CASH', 'Tigo Cash'), ('ECOBANK_MOBILE', 'Ecobank Mobile'), ('UBA_MOBILE', 'UBA Mobile'), ('ZENITH_MOBILE', 'Zenith Mobile'), ('ACCESS_MOBILE', 'Access Mobile'), ('FIDELITY_MOBILE', 'Fidelity Mobile')], max_length=20),
        ),
    ]
