# Generated by Django 5.2.3 on 2025-07-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_beneficiaire_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_iso', models.CharField(max_length=3, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('devise', models.CharField(max_length=3)),
                ('prefixe_tel', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('flag_emoji', models.CharField(default='🇸🇳', max_length=10)),
                ('limite_envoi_min', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('limite_envoi_max', models.DecimalField(decimal_places=2, default=500000, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='CorridorTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('temps_livraison_min', models.PositiveIntegerField(help_text='Minutes minimum')),
                ('temps_livraison_max', models.PositiveIntegerField(help_text='Minutes maximum')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('commission_fixe', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('montant_min_corridor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_max_corridor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nb_transactions', models.PositiveIntegerField(default=0)),
                ('volume_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_succes', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pays_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridors_entrants', to='transactions.pays')),
                ('pays_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridors_sortants', to='transactions.pays')),
            ],
            options={
                'unique_together': {('pays_origine', 'pays_destination')},
            },
        ),
        migrations.CreateModel(
            name='ServicePaiementInternational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('type_service', models.CharField(choices=[('MTN_MONEY', 'MTN Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('MOOV_MONEY', 'Moov Money'), ('WESTERN_UNION', 'Western Union'), ('MONEYGRAM', 'MoneyGram')], max_length=20)),
                ('code_service', models.CharField(max_length=10)),
                ('api_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('frais_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frais_fixe', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('frais_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frais_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('limite_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regex_telephone', models.CharField(help_text='Regex pour valider les numéros', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='transactions.pays')),
            ],
        ),
        migrations.CreateModel(
            name='TauxChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise_origine', models.CharField(max_length=3)),
                ('devise_destination', models.CharField(max_length=3)),
                ('taux', models.DecimalField(decimal_places=6, max_digits=12)),
                ('taux_inverse', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(default='xe.com', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('marge_achat', models.DecimalField(decimal_places=4, default=0.02, max_digits=5)),
                ('marge_vente', models.DecimalField(decimal_places=4, default=0.02, max_digits=5)),
            ],
            options={
                'indexes': [models.Index(fields=['devise_origine', 'devise_destination'], name='transaction_devise__50a423_idx'), models.Index(fields=['last_updated'], name='transaction_last_up_4219d1_idx')],
                'unique_together': {('devise_origine', 'devise_destination')},
            },
        ),
        migrations.CreateModel(
            name='TransactionInternationale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_applique', models.DecimalField(decimal_places=6, max_digits=12)),
                ('montant_origine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_destination', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_service_origine', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frais_service_destination', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commission_corridor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frais_change', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reference_externe', models.CharField(blank=True, max_length=50)),
                ('temps_traitement_estime', models.PositiveIntegerField()),
                ('date_livraison_estimee', models.DateTimeField()),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.corridortransfert')),
                ('pays_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='transactions.pays')),
                ('pays_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envois', to='transactions.pays')),
                ('service_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_destination', to='transactions.servicepaiementinternational')),
                ('service_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_origine', to='transactions.servicepaiementinternational')),
                ('transaction_locale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension_internationale', to='transactions.transaction')),
            ],
        ),
    ]
