# Generated by Django 5.2.3 on 2025-07-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_servicepaiementinternational_type_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='limite_envoi_max',
            field=models.DecimalField(decimal_places=2, default=500000, help_text='Montant maximum pour envoi vers ce pays', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pays',
            name='limite_envoi_min',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Montant minimum pour envoi vers ce pays', max_digits=10),
        ),
    ]
