# Generated by Django 5.2.3 on 2025-07-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_add_pays_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepaiementinternational',
            name='numero_longueur',
            field=models.PositiveIntegerField(blank=True, help_text='Longueur du numéro de téléphone local (sans préfixe)', null=True),
        ),
    ]
